import { motion } from "framer-motion";
import {
  FaFileAlt,
  FaBrain,
  FaChartLine,
  FaRoad,
  FaBriefcase,
  FaUserTie,
} from "react-icons/fa";

const features = [
  {
    icon: <FaFileAlt size={30} />,
    title: "Resume Analysis",
    desc: "Extract skills, projects and education automatically.",
    className: "col-span-2 row-span-1",
  },
  {
    icon: <FaBrain size={30} />,
    title: "AI Skill Gap",
    desc: "Find missing skills instantly.",
    className: "col-span-1 row-span-1",
  },
  {
    icon: <FaChartLine size={30} />,
    title: "ATS Score",
    desc: "Know how recruiters see your resume.",
    className: "col-span-1 row-span-1",
  },
  {
    icon: <FaRoad size={30} />,
    title: "Learning Roadmap",
    desc: "Personalized roadmap generated by AI.",
    className: "col-span-2 row-span-1",
  },
  {
    icon: <FaBriefcase size={30} />,
    title: "Job Match %",
    desc: "Check compatibility with target roles.",
    className: "col-span-1 row-span-1",
  },
  {
    icon: <FaUserTie size={30} />,
    title: "Interview Prep",
    desc: "AI generated interview questions.",
    className: "col-span-1 row-span-1",
  },
];

const Features = () => {
  return (
    <section   id="features" className="max-w-7xl mx-auto px-8 py-32">
      <div className="text-center mb-16">
        <h2 className="text-5xl font-bold">
          Everything You Need
        </h2>

        <p className="text-slate-400 mt-4 text-lg">
          One platform for resume analysis,
          roadmap generation and interview preparation.
        </p>
      </div>

      <div className="grid md:grid-cols-3 gap-6 auto-rows-[220px]">

        {features.map((feature, index) => (
          <motion.div
            key={index}
            initial={{ opacity: 0, y: 60 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4 }}
            viewport={{ once: true }}
            className={`
              ${feature.className}
              rounded-3xl
              border
              border-white/10
              bg-white/5
              backdrop-blur-xl
              p-8
              hover:border-cyan-400
              hover:-translate-y-2
              duration-300
            `}
          >
            <div className="text-cyan-400">
              {feature.icon}
            </div>

            <h3 className="text-2xl font-bold mt-6">
              {feature.title}
            </h3>

            <p className="text-slate-400 mt-4">
              {feature.desc}
            </p>
          </motion.div>
        ))}
      </div>
    </section>
  );
};

export default Features;